### ISSUE TITLE
Adopt GB18030-2022

### ISSUE THREAD

**Issue by lucacasonato** [hsivonen/encoding_rs#107]
See https://github.com/whatwg/encoding/pull/336

The changes required seem to mostly be in data files. It seems not too complex.

**Comment by hsivonen** [comment]
> The changes required seem to mostly be in data files. It seems not too complex.

There are additional sources of complexity:

1. The generator is still on Python 2, so it need to be run in a VM running an old OS.
2. The upstream license has changed, so I need to review which additional places need to point to the WHATWG license.
3. The test case generator now doesn't generate the expected test cases, since it works directly with the gb18030-ranges data, which now has entries that apply to decode but are overridden for encode.

I'll make an initial PR today, but it might not have enough time to get this to a releasable state immediately. (At least this isn't too urgent in practice.)

**Comment by hsivonen** [comment]
See https://github.com/hsivonen/encoding_rs/pull/108 for progress.

**Comment by hsivonen** [comment]
Released as 0.8.35.

**Comment by lucacasonato** [comment]
Thanks!
