### ISSUE TITLE
Convert generating_encoding_data.py to a Rust build script

### ISSUE THREAD

**Issue by wizzwizz4** [hsivonen/encoding_rs#43]
This is basically the entire purpose of build scripts. From [the book](https://doc.rust-lang.org/cargo/reference/build-scripts.html):

> Some example use cases of the build command are: […]
> 
>   * Generating a Rust module from a specification.

Would it be better to include an Encoding Standard .json in the codebase, and use a build script to generate data.rs, instead of having a Python script doing that job? (I don't know how powerful git submodules are, but it might be possible to get them to automatically update the JSON too.)

**Comment by hsivonen** [comment]
When I started this, I wasn't familiar enough with Rust to write the code generation part in Rust. If I started now, I'd write the code generator in Rust, too. But since the generator exists, the benefit of rewriting it in Rust is low.

The inputs to the code generation change very rarely, so even if the code generation was written in Rust, it's unclear if it was a good idea to run it as a build script instead of running it manually and committing the output in git.

The README deliberately says to use a particular snapshot of the Encoding Standard. Autoupdating is undesirable and updates should be manually checked. (There haven't been updates to the data after the documented snapshot.)
