### ISSUE TITLE
optimizing encode function or giving better idea to encode utf8 to ansi

### ISSUE THREAD

**Issue by bobi6666** [hsivonen/encoding_rs#91]
hello, I found out that when I use the encode method, which also returns a vector, the conversion from utf8 to ansi is much slower, and therefore I would like to ask if there is a way to optimize the encode function, or if not, a better idea than encode utf8 to ansi and also calculate with the fact that there are unmappable chars

**Comment by hsivonen** [comment]
This crate deliberately de-emphasizes the performance of converting _to_ legacy encodings. A reasonable way to make them faster for users who really need encode to legacy encodings instead of being able to use UTF-8 for outgoing data, would be providing a compile-time option to use [`icu_collections::codepointtrie::CodePointTrie`](https://docs.rs/icu_collections/latest/icu_collections/codepointtrie/struct.CodePointTrie.html) as the lookup data structure. Unfortunately, building the `CodePointTrie`-compatible static data layout isn't a good fit for the current Python2 code generation script, so implementing this would be a non-trivial undertaking.

**Comment by hsivonen** [comment]
See [the wasm-based builder](https://github.com/unicode-org/icu4x/tree/main/components/collections/codepointtrie_builder) for computing the data structure and the [`databake` crate](https://crates.io/crates/databake) for generating `.rs` files with the data.

**Comment by bobi6666** [comment]
is there any alternative i can use to resolve this problem?

2022-10-17 9:45 GMT+02:00, Henri Sivonen ***@***.***>:

**Comment by hsivonen** [comment]
> is there any alternative i can use to resolve this problem?

The [`encoding`](https://crates.io/crates/encoding/) crate might be faster at converting _to_ single-byte legacy encodings.
